import { jsPDF } from "jspdf";
import { Block, FieldLog, ChemicalApp } from "@/lib/store";
import { format } from "date-fns";

interface PdfData {
  date: Date;
  ranchName: string;
  blocks: Block[];
  logs: FieldLog[];
  apps: ChemicalApp[];
  totals: {
    acres: number;
    spend: number;
    materials: Record<string, string>;
  };
  issuesCount: number;
}

export function generateTodayPacketPdf(data: PdfData): string {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4"
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("KEBB AG - Daily Operations Packet", 14, y);
  
  y += 8;
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Ranch: ${data.ranchName}`, 14, y);
  doc.text(`Date: ${format(data.date, 'MMMM d, yyyy')}`, 14, y + 6);
  
  y += 20;

  // Summary Totals
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Executive Summary", 14, y);
  
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(`Total Blocks Worked: ${data.blocks.length}`, 14, y);
  doc.text(`Total Acres Touched: ${data.totals.acres.toFixed(1)}`, 14, y + 6);
  doc.text(`Estimated Material Spend: $${data.totals.spend.toLocaleString()}`, 14, y + 12);
  
  if (data.issuesCount > 0) {
    doc.setTextColor(220, 38, 38); // Red
    doc.text(`ATTENTION: ${data.issuesCount} flags need review in system`, 14, y + 18);
    doc.setTextColor(0, 0, 0); // Reset
  }

  y += 28;

  // Materials Applied
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Total Materials Applied", 14, y);
  
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  
  const matEntries = Object.entries(data.totals.materials);
  if (matEntries.length === 0) {
    doc.text("No materials recorded today.", 14, y);
    y += 8;
  } else {
    matEntries.forEach(([mat, amount]) => {
      doc.text(`• ${mat}: ${amount}`, 14, y);
      y += 6;
    });
    y += 2;
  }

  y += 10;

  // Block Details
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Work Log by Block", 14, y);
  y += 10;

  if (data.blocks.length === 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.text("No logs recorded for today.", 14, y);
  } else {
    data.blocks.forEach(block => {
      // Check page break
      if (y > 260) {
        doc.addPage();
        y = 20;
      }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.text(`${block.name} (${block.acreage} AC - ${block.variety})`, 14, y);
      y += 6;

      const blockLogs = data.logs.filter(l => l.blockId === block.id);
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      
      blockLogs.forEach(log => {
        const app = data.apps.find(a => a.id === `app-${log.id}`);
        const flagMarker = (app?.costStatus === 'UNIT_MISMATCH' || !log.amount) ? '[FLAG]' : '';
        
        // Try to parse time from ISO string, fallback to default
        let timeStr = "";
        try {
           const logDate = new Date(log.date);
           if (log.date.includes('T')) {
             timeStr = format(logDate, 'h:mm a') + " - ";
           }
        } catch(e) {}

        const text = `  • ${timeStr}${log.actionType}: ${log.material} @ ${log.amount} ${log.unit} ${flagMarker}`;
        doc.text(text, 14, y);
        y += 5;
      });
      y += 5;
    });
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by KEBB Ag™", 14, 285);

  return doc.output('bloburl');
}
